export const thingsBase = {
  'WEAPON': {
    'COMMON': ['SWORD', 'BOW'],
    'UNCOMMON': ['SHARPED AX','CROSSBOW'],
    'RARE': ['KILLER BLADES', 'GOLDEN BOW'],
    'LEGENDARY': ['KING HALBERD','MAGIC STAFF']
  },
  'HELMET': {
    'COMMON': ['METALIC HELMET','PAPER HELMET WITH MASK'],
    'UNCOMMON': ['CLOSED HELMET', 'STEEL HELMET'],
    'RARE': ['FLYING HAT','EASY ARMET'],
    'LEGENDARY': ['INVISIBLE HAT', 'LEGENDARY DEFENDER']
  },
  'ARMOR': {
    'COMMON': ['CHAIN ARMOR', 'METALIC'],
    'UNCOMMON': ['BRONSE', 'ALUMINUM'],
    'RARE': ['DIAMOND', 'LORD ARMOR'],
    'LEGENDARY': ['DRAGON ARMOR', 'UNICORN SKIN']
  },
  'SHIELD': {
    'COMMON': ['WOODEN SHIELD', 'ROUND SHIELD'],
    'UNCOMMON': ['LONG SHIELD', 'STRONG SHIELD'],
    'RARE': ['DRAGON BON', 'DEFLECTOR'],
    'LEGENDARY': ['FIRE BLOCK', 'IMPERIAL SHIELD']
  }
}